# This file is part of dptwo.
#
# Developed for the LSST Data Management System.
# This product includes software developed by the LSST Project
# (https://www.lsst.org).
# See the COPYRIGHT file at the top-level directory of this distribution
# for details of code ownership.
#
# Use of this source code is governed by a 3-clause BSD-style
# license that can be found in the LICENSE file.
"""Utilities for writing LaTeX parameter definitions for the DP2 paper."""

from __future__ import annotations

__all__ = [
    "DP2Parameters",
    "addParameter",
    "formatParameter",
]

from collections import OrderedDict
from collections.abc import Iterable, Mapping
from pathlib import Path
from typing import Any

from .utils import num2word, round_sf

AUTOGEN_HEADER = [
    "% These parameters are automatically generated by python/lsst/dptwo/parameters.py.",
    "% Do NOT manually edit this file.",
    "% If you need to change or add a parameter, update the code that populates",
    "% the DP2Parameters store and then re-run the writer.",
]
ANGULAR_UNITS = ("\\arcsec", "\\arcmin", "\\degree")
ANGULAR_DECIMAL_MARKERS = {
    "\\arcsec": "\\farcs",
    "\\arcmin": "\\farcm",
    "\\degree": "\\fdg",
}
DEFAULT_OUTPUT_PATH = Path("sections/new_parameters.tex")


class DP2Parameters:
    """Store extracted parameters and render them as LaTeX commands."""

    def __init__(self) -> None:
        self._values: "OrderedDict[str, Any]" = OrderedDict()
        self._units: dict[str, str] = {}

    @property
    def values(self) -> Mapping[str, Any]:
        """Return the stored parameter values in insertion order."""
        return self._values

    @property
    def units(self) -> Mapping[str, str]:
        """Return the stored parameter units."""
        return self._units

    def add(
        self, name: str, value: Any, unit: str | None = None, *,
            sig: int | None = None) -> None:
        """Add or update a parameter in the store.
        """
        if sig is not None:
            value = round_sf(value, sig=sig)

        self._values[name] = value
        if unit is not None:
            self._units[name] = unit
        elif name in self._units:
            del self._units[name]

    def add_many(
        self,
        parameters: Mapping[str, Any] | Iterable[tuple[str, Any]],
        *,
        units: Mapping[str, str] | None = None,
    ) -> None:
        """Add many parameters from a mapping or iterable of pairs.

        """
        items = parameters.items() if isinstance(parameters, Mapping) else parameters
        for name, value in items:
            unit = None if units is None else units.get(name)
            self.add(name, value, unit=unit)

    def format_parameter(self, name: str) -> str:
        """Format a stored parameter as a LaTeX ``\\newcommand``.
        """
        value = self._values[name]
        value_text = self._format_value(value)
        unit = self._units.get(name)

        if unit:
            value_text, unit = self._format_unit(value_text, unit)
            return f"\\newcommand{{\\{name}}}{{{value_text}{unit}\\xspace}}\n"

        return f"\\newcommand{{\\{name}}}{{{value_text}\\xspace}}\n"

    def to_latex(self) -> str:
        """Render the full parameter file contents."""
        lines = list(AUTOGEN_HEADER)
        lines.append("")
        lines.extend(self.format_parameter(name).rstrip("\n") for name in self._values)
        lines.append("")
        return "\n".join(lines)

    def write(self, output_path: str | Path = DEFAULT_OUTPUT_PATH) -> Path:
        """Write the rendered parameter file to disk."""
        path = Path(output_path).resolve()
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(self.to_latex(), encoding="utf-8")
        return path

    @staticmethod
    def _format_value(value: Any) -> str:
        if isinstance(value, float):
            return f"{value:.3f}".rstrip("0").rstrip(".")
        return str(value)

    @staticmethod
    def _format_unit(value_text: str, unit: str) -> tuple[str, str]:
        if unit.startswith(ANGULAR_UNITS):
            for angular_unit, marker in ANGULAR_DECIMAL_MARKERS.items():
                if unit.startswith(angular_unit) and "." in value_text:
                    return value_text.replace(".", marker, 1), unit.replace(angular_unit, "", 1)
            return value_text, unit
        return value_text, f"\\xspace {unit}"


def addParameter(
    params: DP2Parameters,
    name: str,
    value: Any,
    unit: str | None = None,
    **kwargs: Any,
) -> DP2Parameters:
    """Backward-compatible wrapper around :meth:`DP2Parameters.add`."""
    params.add(name, value, unit=unit, sig=kwargs.get("sig"))
    return params


def formatParameter(params: DP2Parameters, name: str) -> str:
    """Backward-compatible wrapper around :meth:`DP2Parameters.format_parameter`."""
    return params.format_parameter(name)
