[tox]
envlist = py

[testenv]
skip_install = true
deps =
    pytest
    lsst-utils
    lsst-daf-butler
    pandas
    numpy
setenv =
    PYTHONPATH = {toxinidir}/src:{toxinidir}/python
commands =
    pytest {posargs:tests}
