name: Process Author signup  form

on:
  workflow_dispatch:
  schedule:
    #  UTC min hour day month dayOfWeek
    - cron: '40 6 * * *'

jobs:
  authorform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          ref: tickets/DM-55981
          fetch-depth: 0 # full history for metadata
          submodules: true

      # new authos may be in lsst-txmf and its giiod to pull that up anyway
      - name: Update lsst-texmf submodule to latest remote
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive --remote lsst-texmf

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.13

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install uv
          python -m uv pip install --system -r lsst-texmf/requirements.txt

      - name: process form
        env:
          CLIENT: ${{ secrets.FORM_ACCESS_CLIENT }}
          TOKEN_PASSPHRASE: ${{ secrets.TOKEN_PASSPHRASE }}
        run: |
          echo $CLIENT >> client_secret.json
          SKIP=`cat skip.count`
          ./lsst-texmf/bin/decrypt_secret.sh $TOKEN_PASSPHRASE
          make skip
          SKIP2=`cat skip.count`
          if [ "$SKIP2" -gt "$SKIP" ]; then
              echo "Got new author $SKIP2 , had $SKIP"
          else
              echo "Got no new author $SKIP2 ==  $SKIP"
          fi

      - name: Check diff
        shell: bash
        run: |
          set -euo pipefail

          echo "Current repository status:"
          git status --short --ignore-submodules=none

          echo "Submodule commit change:"
          git diff --submodule=log \
            --ignore-submodules=dirty \
            HEAD -- lsst-texmf

          if git diff --quiet \
            --ignore-submodules=dirty \
            HEAD -- authors.yaml skip.count lsst-texmf; then
            echo "CHANGED=false" >> "$GITHUB_ENV"
            echo "No authors or lsst-texmf changes"
          else
            echo "CHANGED=true" >> "$GITHUB_ENV"
            echo "Authors or lsst-texmf changed"
          fi
      - name: Commit new authors.yaml
        if: env.CHANGED == 'true'
        run: | # cpr adds all files - these should not be added
          rm client_secret.json token.pickle
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m " Author updates from google form and or new texmf " authors.yaml skip.count lsst-texmf

      - name: Create Pull Request
        id: cpr
        if: env.CHANGED == 'true'
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.WOM_RTN_115_PAT }}
          base: tickets/DM-55981
          branch: update-authors-from-form
          branch-suffix: short-commit-hash
          title: Automatic authors  update
          commit-message: authors update from google form
          body: |
            Update authors.yaml from new entries in the Google form
            and update the lsst-texmf submodule reference.
